version: '3.5'

services:

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  db:
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
    image: postgres:latest
